# Generated by Django 4.0.4 on 2022-05-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iswc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('contributors', models.TextField()),
                ('iswc', models.CharField(blank=True, default=None, max_length=13, null=True, unique=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='iswc',
            constraint=models.UniqueConstraint(condition=models.Q(('iswc__isnull', True), ('iswc__length__gt', 0), _connector='OR'), fields=('title', 'contributors'), name='unique__title__contributors__when__iswc__null'),
        ),
        migrations.AddConstraint(
            model_name='iswc',
            constraint=models.UniqueConstraint(fields=('iswc',), name='unique__iswc__when__iswc__not_null'),
        ),
    ]
