# Generated by Django 4.0.4 on 2022-05-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iswcsview', '0002_alter_iswc_iswc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iswc',
            name='iswc',
            field=models.CharField(blank=True, default=None, max_length=13, null=True, unique=True),
        ),
    ]
